defaults.org=hitek-y6
defaults.project=android
auth.token=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